import type { Metadata } from 'next'
import LegalPage from '@/components/ui/LegalPage'

export const metadata: Metadata = {
  title: 'Disclaimer | Operon Automation',
  description: 'Disclaimer for Operon Automation, Revenue Autopilot, and the Revenue Leak Scanner.',
}

export default function DisclaimerPage() {
  return (
    <LegalPage title="Disclaimer" lastUpdated="May 20, 2025">
      <h2>Revenue Leak Scores and Estimates</h2>
      <p>
        Revenue Leak Scores, reports, and estimated opportunity figures generated by Operon Automation, the Revenue Leak Scanner, and Revenue Autopilot are informational only and based on the information provided by the user.
      </p>
      <p>
        <strong>Operon Automation does not guarantee specific financial results, revenue increases, customer acquisition outcomes, or any other specific business improvement.</strong> All scores, estimates, and recommendations are provided for educational and planning purposes and should not be relied upon as a guarantee of business performance.
      </p>

      <h2>No Financial or Legal Advice</h2>
      <p>
        Nothing on operonauto.com or within Operon Automation's services constitutes financial, legal, accounting, or professional advice of any kind. You should consult qualified professionals before making significant business, financial, or operational decisions.
      </p>

      <h2>Results May Vary</h2>
      <p>
        Any examples, case studies, testimonials, or results referenced on our website or in our materials represent individual experiences and results. Individual results will vary based on business type, market conditions, execution, and many other factors. Past performance or illustrated examples are not indicative of future results.
      </p>

      <h2>Estimated Opportunity Figures</h2>
      <p>
        When Operon Automation references &quot;estimated opportunity,&quot; &quot;potential leak,&quot; or similar language, these figures are estimates based on common industry patterns and the information provided by the business owner. They do not represent guaranteed or certain revenue amounts.
      </p>

      <h2>Third-Party Tools and Services</h2>
      <p>
        Operon Automation may recommend or integrate with third-party tools, platforms, and services. We are not responsible for the performance, accuracy, or results of third-party services. Our mention of any third-party product does not constitute an endorsement or guarantee.
      </p>

      <h2>Automation Performance</h2>
      <p>
        The performance of automated systems, including follow-up agents, review request agents, and other Autopilot features, depends on many factors outside of Operon's control, including customer behavior, market conditions, message deliverability, and business-specific circumstances. We do not guarantee that automating a business process will produce specific results.
      </p>

      <h2>Accuracy of Information</h2>
      <p>
        While we strive to provide accurate and up-to-date information on operonauto.com, we make no representations or warranties about the completeness, reliability, or accuracy of the information. Information may be updated or changed without notice.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about this disclaimer? Contact us at ceo@operonauto.com.
      </p>
    </LegalPage>
  )
}
